-- Add hero and image columns to settings table
ALTER TABLE settings ADD COLUMN IF NOT EXISTS hero_title VARCHAR(500) DEFAULT NULL;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS hero_description TEXT DEFAULT NULL;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS banner_image VARCHAR(255) DEFAULT NULL;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS logo_image VARCHAR(255) DEFAULT NULL;
